export const GET_PAGE = 'PAGE::GET';
export const GET_PAGE_SUCCESS = 'PAGE::GET_SUCCESS';
export const GET_PAGE_FAILURE = 'PAGE::GET_FAILURE';

export const UPDATE_PAGE_LAYOUT = 'PAGE::UPDATE_LAYOUT';
export const UPDATE_PAGE_LAYOUT_SUCCESS = 'PAGE::UPDATE_LAYOUT_SUCCESS';
export const UPDATE_PAGE_LAYOUT_FAILURE = 'PAGE::UPDATE_LAYOUT_FAILURE';

export const ADD_WIDGET = 'PAGE::ADD_WIDGET';
export const ADD_WIDGET_SUCCESS = 'PAGE::ADD_WIDGET_SUCCESS';
export const ADD_WIDGET_FAILURE = 'PAGE::ADD_WIDGET_FAILURE';

export const TOGGLE_EDITING = 'PAGE::TOGGLE_EDITING';

export const REMOVE_WIDGET_FROM_PAGE = 'PAGE::REMOVE_WIDGET'
export const REMOVE_WIDGET_FROM_PAGE_SUCCESS = 'PAGE::REMOVE_WIDGET_SUCCESS'
export const REMOVE_WIDGET_FROM_PAGE_FAILURE = 'PAGE::REMOVE_WIDGET_FAILURE'