module.exports = {
  playerName: 'Joe',
  characterName: 'Smash',
  className: 'Barbarian',
  subClass: 'Bezerker',
  level: '8',
  race: 'Gloiath',
  alignment: 'Chaotic Good',
  xp: 23500,
  ac: 17,
  initiative: 7,
  speed: 40,
  inspiration: '1d4',
  proficiencyBonus: 3,
  attributes: [
    {
      name: 'strength',
      abbv: 'str',
      value: 20,
      modifier: 5,
      proficient: true,
      notes: 'adv. when in a rage',
    },
    {
      name: 'dexterity',
      abbv: 'dex',
      value: 15,
      modifier: 2,
      proficient: false,
      notes: '',
    },
    {
      name: 'constitution',
      abbv: 'con',
      value: 18,
      modifier: 4,
      proficient: true,
      notes: '',
    },
    {
      name: 'intelligence',
      abbv: 'int',
      value: 9,
      modifier: -1,
      proficient: false,
      notes: '',
    },
    {
      name: 'wisdom',
      abbv: 'wis',
      value: 12,
      modifier: 1,
      proficient: false,
      notes: '',
    },
    {
      name: 'charisma',
      abbv: 'cha',
      value: 10,
      modifier: 0,
      proficient: false,
      notes: '',
    },
  ],
  skills: [
    {
      name: 'Acrobatics',
      modifiers: [], // something like { name: 'Boots of Jumping', value: 1, notes: 'Got these from killing the goblin king'}
      type: 'dex',
      proficient: false,
      notes: '',
    },
    {
      name: 'Animal Handling',
      modifiers: [],
      type: 'wis',
      proficient: true,
      notes: '',
    },
    {
      name: 'Arcana',
      modifiers: [],
      type: 'int',
      proficient: false,
      notes: '',
    },
    {
      name: 'Athletics',
      modifiers: [],
      type: 'str',
      proficient: true,
      notes: 'adv. when rageing',
    },
    {
      name: 'Deception',
      modifiers: [],
      type: 'cha',
      proficient: false,
      notes: '',
    },
    {
      name: 'History',
      modifiers: [],
      type: 'int',
      proficient: false,
      notes: '',
    },
    {
      name: 'Insight',
      modifiers: [],
      type: 'wis',
      proficient: false,
      notes: '',
    },
    {
      name: 'Intimidation',
      modifiers: [],
      type: 'cha',
      proficient: false,
      notes: '',
    },
    {
      name: 'Investigation',
      modifiers: [],
      type: 'int',
      proficient: false,
      notes: '',
    },
    {
      name: 'Medicine',
      modifiers: [],
      type: 'wis',
      proficient: false,
      notes: '',
    },
    {
      name: 'Nature',
      modifiers: [],
      type: 'int',
      proficient: false,
      notes: '',
    },
    {
      name: 'Perception',
      modifiers: [],
      type: 'wis',
      proficient: false,
      notes: '',
    },
    {
      name: 'Performance',
      modifiers: [],
      type: 'cha',
      proficient: false,
      notes: '',
    },
    {
      name: 'Persuasion',
      modifiers: [],
      type: 'cha',
      proficient: false,
      notes: '',
    },
    {
      name: 'Religion',
      modifiers: [],
      type: 'int',
      proficient: false,
      notes: '',
    },
    {
      name: 'Sleight of Handling',
      modifiers: [],
      type: 'dex',
      proficient: false,
      notes: '',
    },
    {
      name: 'Stealth',
      modifiers: [],
      type: 'dex',
      proficient: false,
      notes: '',
    },
    {
      name: 'Survival',
      modifiers: [],
      type: 'wis',
      proficient: true,
      notes: '',
    },
  ],
  languages: ['Common', 'Giant'],
  proficiencies: [],
  money: {
    cp: null,
    sp: null,
    ep: null,
    gp: null,
    pp: null,
  },
  equipment: {
    armor: [], // { name, ac, modifier, modifierMax, preqStr, stealth, weight, notes }
    weapons: [{
      name: '+1 Warhammer',
      dmg: ['1d8+1', '1d10+1'],
      dmgType: 'bludgening',
      properties: 'Versatile (ld10)',
      notes: '',
    }], // { name, modifier, dmg, stat, range, weight, notes }
    other: [],
  },
  status: [],
  featuresAndTraits: '',
  savingThrows: [],
  health: {
    hitDice: '1d12',
    numOfHitDice: 8,
    currentHp: 76,
    totalHp: 76,
    maxHp: 76,
    tempHp: 0,
    deathSaves: [], // [true, false, false, true, true] === 3 success 2 fails
    notes: '',
  },
  personality: {
    traits: '',
    ideals: '',
    bonds: '',
    flaws: '',
    backstory: '',
    notes: '',
  },
  appearance: {
    age: null,
    height: '7\'5',
    weight: '315lbs',
    eyes: 'grey',
    skin: 'grey with tattoos',
    hair: 'bald',
    notes: '',
  },
  spells: [],
  spellSlots: [],
}