export const GET_LIST = 'LIST::GET';
export const GET_LIST_SUCCESS = 'LIST::GET_SUCCESS';
export const GET_LIST_FAILURE = 'LIST::GET_FAILURE';

export const ADD_LIST_ITEM = 'LIST::ADD_ITEM';
export const ADD_LIST_ITEM_SUCCESS = 'LIST::ADD_ITEM_SUCCESS';
export const ADD_LIST_ITEM_FAILURE = 'LIST::ADD_ITEM_FAILURE';

export const UPDATE_LIST_ITEM = 'LIST::UPDATE_ITEM';
export const UPDATE_LIST_ITEM_SUCCESS = 'LIST::UPDATE_ITEM_SUCCESS';
export const UPDATE_LIST_ITEM_FAILURE = 'LIST::UPDATE_ITEM_FAILURE';

export const REORDER_LIST_ITEMS = 'LIST::REORDER_ITEMS';
export const REORDER_LIST_ITEMS_SUCCESS = 'LIST::REORDER_ITEMS_SUCCESS';
export const REORDER_LIST_ITEMS_FAILURE = 'LIST::REORDER_ITEMS_FAILURE';

export const REMOVE_LIST_ITEM = 'LIST::REMOVE_ITEM';
export const REMOVE_LIST_ITEM_SUCCESS = 'LIST::REMOVE_ITEM_SUCCESS';
export const REMOVE_LIST_ITEM_FAILURE = 'LIST::REMOVE_ITEM_FAILURE';

export const CREATE_LIST = 'LIST::CREATE';
export const CREATE_LIST_SUCCESS = 'LIST::CREATE_SUCCESS';
export const CREATE_LIST_FAILURE = 'LIST::CREATE_FAILURE';

export const UPDATE_LIST = 'LIST::UPDATE';
export const UPDATE_LIST_SUCCESS = 'LIST::UPDATE_SUCCESS';
export const UPDATE_LIST_FAILURE = 'LIST::UPDATE_FAILURE';

export const DELETE_LIST = 'LIST::DELETE';
export const DELETE_LIST_SUCCESS = 'LIST::DELETE_SUCCESS';
export const DELETE_LIST_FAILURE = 'LIST::DELETE_FAILURE';
