// index of the array item is the modifier, so modifiers[18] = 4, modifiers[9] = -1, etc.
export const modifiers = [
  -5, -5, -4, -4, -3, -3, -2, -2, -1, -1,
  0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5,
  5, 6, 6, 7, 7, 8, 8, 9, 9, 10,
];

export const characterSchemas = [{
  name: 'D&D 5th Edition',
  schema: {
    ac: {
      base: 10,
      notes: '',
      modifiers: [],
      attributes: ['dex'],
      maxAttrMod: -1,
    },
    xp: 0,
    race: '',
    level: '1',
    money: {
      cp: 0,
      ep: 0,
      gp: 0,
      pp: 0,
      sp: 0,
    },
    speed: {
      base: 30,
      modifiers: [],
    },
    health: {
      maxHp: '0',
      notes: '',
      tempHp: '0',
      hitDice: '1d6',
      totalHp: 0,
      currentHp: 0,
      deathSaves: [],
      totalHitDice: 1,
    },
    skills: [
      {
        name: 'Acrobatics',
        type: 'dex',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Animal Handling',
        type: 'wis',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Arcana',
        type: 'int',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Athletics',
        type: 'str',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Deception',
        type: 'cha',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'History',
        type: 'int',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Insight',
        type: 'wis',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Intimidation',
        type: 'cha',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Investigation',
        type: 'int',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Medicine',
        type: 'wis',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Nature',
        type: 'int',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Perception',
        type: 'wis',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Performance',
        type: 'cha',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Persuasion',
        type: 'cha',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Religion',
        type: 'int',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Sleight of Hand',
        type: 'dex',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Stealth',
        type: 'dex',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      },
      {
        name: 'Survival',
        type: 'wis',
        notes: '',
        proficient: false,
        bonusModifier: 0,
      }
    ],
    spells: [],
    status: [],
    attacks: [],
    features: [],
    subClass: '',
    alignment: '',
    className: '',
    equipment: [],
    attributes: [
      {
        abbv: 'str',
        name: 'Strength',
        notes: '',
        value: 0,
        bonusModifier: 0,
      },
      {
        abbv: 'dex',
        name: 'Dexterity',
        notes: '',
        value: 0,
        bonusModifier: 0,
      },
      {
        abbv: 'con',
        name: 'Constitution',
        notes: '',
        value: 0,
        bonusModifier: 0,
      },
      {
        abbv: 'int',
        name: 'Intelligence',
        notes: '',
        value: 0,
        bonusModifier: 0,
      },
      {
        abbv: 'wis',
        name: 'Wisdom',
        notes: '',
        value: 0,
        bonusModifier: 0,
      },
      {
        abbv: 'cha',
        name: 'Charisma',
        notes: '',
        value: 0,
        bonusModifier: 0,
      }
    ],
    background: '',
    initiative: {
      notes: '',
      modifiers: []
    },
    spellSlots: [],
    inspiration: '',
    personality: '',
    savingThrows: [
        {
            name: 'Strength',
            type: 'str',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        },
        {
            name: 'Dexterity',
            type: 'dex',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        },
        {
            name: 'Constitution',
            type: 'con',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        },
        {
            name: 'Intelligence',
            type: 'int',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        },
        {
            name: 'Wisdom',
            type: 'wis',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        },
        {
            name: 'Charisma',
            type: 'cha',
            notes: '',
            proficient: false,
            bonusModifier: 0,
        }
    ],
    proficiencyBonus: 1,
    languagesAndProficiencies: '',
  },
}];
